# Generated by Django 4.1.4 on 2023-01-30 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderedfood',
            options={'verbose_name': 'Ordered Food', 'verbose_name_plural': 'Ordered Food'},
        ),
    ]
