# Generated by Django 4.1.4 on 2023-01-31 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_vendor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='vendor',
            new_name='vendors',
        ),
    ]
